on:
    push:
        branches:
            - master



            



jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: "docker login"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}

      - name: "docker build image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME}}/monaa .

      - name: "docker push"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/monaa
      
